version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_db
    ports:
      - 5432:5432
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        APP_CODE: /usr/src/virtual_office_crm_backend
    command: npm run dev
    ports:
      - 8080:8080
    volumes:
      - /usr/src/virtual_office_crm_backend/node_modules
      - ./backend:/usr/src/virtual_office_crm_backend
    environment:
      APP_PORT: 8080
      DB_CLIENT: pg
      DB_USER: postgres_user
      DB_HOST: db
      DB_PASSWORD: password
      DB_NAME: postgres_db