version: '3'
services:
  aws_s3:
    container_name: pvocrm_aws_s3
    image: lphoward/fake-s3
    ports:
      - 4569:4569
  redis:
    container_name: pvocrm_redis
    image: redis
    ports:
      - 6379:6379
  db:
    container_name: pvocrm_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
  backend:
    container_name: pvocrm_backend
    build:
      context: ./app/backend
      dockerfile: Dockerfile
      args:
        APP_CODE: /usr/src/pvocrm_backend
    depends_on:
      - aws_s3
      - db
      - redis
    ports:
      - 8080:8080
    environment:
      BACKEND_APP_PORT: 8080
      DB_CLIENT: pg
      DB_USER: postgres
      DB_HOST: db
      DB_PASSWORD: docker
      DB_NAME: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
  frontend:
    container_name: pvocrm_frontend
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
      args:
        APP_CODE: /usr/src/pvocrm_frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      FRONTEND_APP_PORT: 3000 
      BACKEND_HOST: backend
      BACKEND_PORT: 8080