version: '3'
services:
  db:
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/personal/pvocrm
  backend:
    command: npm run dev
    volumes:
      - /usr/src/pvocrm_backend/node_modules
      - ./app/backend:/usr/src/pvocrm_backend
  frontend:
    command: npm run dev
    volumes:
      - /usr/src/pvocrm_frontend/node_modules
      - ./app/frontend:/usr/src/pvocrm_frontend
  webserver:
    volumes:
      - ./app/webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./temp_dev/myCA.cert:/etc/nginx/myCA.cert
      - ./temp_dev/myCA.key:/etc/nginx/myCA.key
