module.exports = {
  Addresses: require('./Addresses'),
  Cities: require('./Cities'),
  Countries: require('./Countries'),
  Documents: require('./Documents'),
  DocumentsCloud: require('./DocumentsCloud'),
  DocumentsTemporary: require('./DocumentsTemporary'),
  Emails: require('./Emails'),
  LegalEntities: require('./LegalEntities'),
  LegalEntitiesVersion: require('./LegalEntitiesVersion'),
  MailSenderNames: require('./MailSenderNames'),
  MailSenders: require('./MailSenders'),
  MailSubjects: require('./MailSubjects'),
  Mails: require('./Mails'),
  MailsAuditTrails: require('./MailsAuditTrails'),
  MailsAuditTrailsDetails: require('./MailsAuditTrailsDetails'),
  MailsPendingActions: require('./MailsPendingActions'),
  NaturalPeople: require('./NaturalPeople'),
  NaturalPeopleVersion: require('./NaturalPeopleVersion'),
  Phones: require('./Phones'),
  Users: require('./Users')
};
