const { AddressCountries } = require('../../models');

exports.seed = async knex => {
  await knex(AddressCountries.tableName).insert([{
    "id": 1,
    "short_name": "US",
    "name": "United States"
  }, {
    "id": 2,
    "short_name": "CA",
    "name": "Canada"
  }, {
    "id": 3,
    "short_name": "AF",
    "name": "Afghanistan"
  }, {
    "id": 4,
    "short_name": "AL",
    "name": "Albania"
  }, {
    "id": 5,
    "short_name": "DZ",
    "name": "Algeria"
  }, {
    "id": 6,
    "short_name": "AS",
    "name": "American Samoa"
  }, {
    "id": 7,
    "short_name": "AD",
    "name": "Andorra"
  }, {
    "id": 8,
    "short_name": "AO",
    "name": "Angola"
  }, {
    "id": 9,
    "short_name": "AI",
    "name": "Anguilla"
  }, {
    "id": 10,
    "short_name": "AQ",
    "name": "Antarctica"
  }, {
    "id": 11,
    "short_name": "AG",
    "name": "Antigua and/or Barbuda"
  }, {
    "id": 12,
    "short_name": "AR",
    "name": "Argentina"
  }, {
    "id": 13,
    "short_name": "AM",
    "name": "Armenia"
  }, {
    "id": 14,
    "short_name": "AW",
    "name": "Aruba"
  }, {
    "id": 15,
    "short_name": "AU",
    "name": "Australia"
  }, {
    "id": 16,
    "short_name": "AT",
    "name": "Austria"
  }, {
    "id": 17,
    "short_name": "AZ",
    "name": "Azerbaijan"
  }, {
    "id": 18,
    "short_name": "BS",
    "name": "Bahamas"
  }, {
    "id": 19,
    "short_name": "BH",
    "name": "Bahrain"
  }, {
    "id": 20,
    "short_name": "BD",
    "name": "Bangladesh"
  }, {
    "id": 21,
    "short_name": "BB",
    "name": "Barbados"
  }, {
    "id": 22,
    "short_name": "BY",
    "name": "Belarus"
  }, {
    "id": 23,
    "short_name": "BE",
    "name": "Belgium"
  }, {
    "id": 24,
    "short_name": "BZ",
    "name": "Belize"
  }, {
    "id": 25,
    "short_name": "BJ",
    "name": "Benin"
  }, {
    "id": 26,
    "short_name": "BM",
    "name": "Bermuda"
  }, {
    "id": 27,
    "short_name": "BT",
    "name": "Bhutan"
  }, {
    "id": 28,
    "short_name": "BO",
    "name": "Bolivia"
  }, {
    "id": 29,
    "short_name": "BA",
    "name": "Bosnia and Herzegovina"
  }, {
    "id": 30,
    "short_name": "BW",
    "name": "Botswana"
  }, {
    "id": 31,
    "short_name": "BV",
    "name": "Bouvet Island"
  }, {
    "id": 32,
    "short_name": "BR",
    "name": "Brazil"
  }, {
    "id": 33,
    "short_name": "IO",
    "name": "British lndian Ocean Territory"
  }, {
    "id": 34,
    "short_name": "BN",
    "name": "Brunei Darussalam"
  }, {
    "id": 35,
    "short_name": "BG",
    "name": "Bulgaria"
  }, {
    "id": 36,
    "short_name": "BF",
    "name": "Burkina Faso"
  }, {
    "id": 37,
    "short_name": "BI",
    "name": "Burundi"
  }, {
    "id": 38,
    "short_name": "KH",
    "name": "Cambodia"
  }, {
    "id": 39,
    "short_name": "CM",
    "name": "Cameroon"
  }, {
    "id": 40,
    "short_name": "CV",
    "name": "Cape Verde"
  }, {
    "id": 41,
    "short_name": "KY",
    "name": "Cayman Islands"
  }, {
    "id": 42,
    "short_name": "CF",
    "name": "Central African Republic"
  }, {
    "id": 43,
    "short_name": "TD",
    "name": "Chad"
  }, {
    "id": 44,
    "short_name": "CL",
    "name": "Chile"
  }, {
    "id": 45,
    "short_name": "CN",
    "name": "China"
  }, {
    "id": 46,
    "short_name": "CX",
    "name": "Christmas Island"
  }, {
    "id": 47,
    "short_name": "CC",
    "name": "Cocos (Keeling) Islands"
  }, {
    "id": 48,
    "short_name": "CO",
    "name": "Colombia"
  }, {
    "id": 49,
    "short_name": "KM",
    "name": "Comoros"
  }, {
    "id": 50,
    "short_name": "CG",
    "name": "Congo"
  }, {
    "id": 51,
    "short_name": "CK",
    "name": "Cook Islands"
  }, {
    "id": 52,
    "short_name": "CR",
    "name": "Costa Rica"
  }, {
    "id": 53,
    "short_name": "HR",
    "name": "Croatia (Hrvatska)"
  }, {
    "id": 54,
    "short_name": "CU",
    "name": "Cuba"
  }, {
    "id": 55,
    "short_name": "CY",
    "name": "Cyprus"
  }, {
    "id": 56,
    "short_name": "CZ",
    "name": "Czech Republic"
  }, {
    "id": 57,
    "short_name": "CD",
    "name": "Democratic Republic of Congo"
  }, {
    "id": 58,
    "short_name": "DK",
    "name": "Denmark"
  }, {
    "id": 59,
    "short_name": "DJ",
    "name": "Djibouti"
  }, {
    "id": 60,
    "short_name": "DM",
    "name": "Dominica"
  }, {
    "id": 61,
    "short_name": "DO",
    "name": "Dominican Republic"
  }, {
    "id": 62,
    "short_name": "TP",
    "name": "East Timor"
  }, {
    "id": 63,
    "short_name": "EC",
    "name": "Ecudaor"
  }, {
    "id": 64,
    "short_name": "EG",
    "name": "Egypt"
  }, {
    "id": 65,
    "short_name": "SV",
    "name": "El Salvador"
  }, {
    "id": 66,
    "short_name": "GQ",
    "name": "Equatorial Guinea"
  }, {
    "id": 67,
    "short_name": "ER",
    "name": "Eritrea"
  }, {
    "id": 68,
    "short_name": "EE",
    "name": "Estonia"
  }, {
    "id": 69,
    "short_name": "ET",
    "name": "Ethiopia"
  }, {
    "id": 70,
    "short_name": "FK",
    "name": "Falkland Islands (Malvinas)"
  }, {
    "id": 71,
    "short_name": "FO",
    "name": "Faroe Islands"
  }, {
    "id": 72,
    "short_name": "FJ",
    "name": "Fiji"
  }, {
    "id": 73,
    "short_name": "FI",
    "name": "Finland"
  }, {
    "id": 74,
    "short_name": "FR",
    "name": "France"
  }, {
    "id": 75,
    "short_name": "FX",
    "name": "France, Metropolitan"
  }, {
    "id": 76,
    "short_name": "GF",
    "name": "French Guiana"
  }, {
    "id": 77,
    "short_name": "PF",
    "name": "French Polynesia"
  }, {
    "id": 78,
    "short_name": "TF",
    "name": "French Southern Territories"
  }, {
    "id": 79,
    "short_name": "GA",
    "name": "Gabon"
  }, {
    "id": 80,
    "short_name": "GM",
    "name": "Gambia"
  }, {
    "id": 81,
    "short_name": "GE",
    "name": "Georgia"
  }, {
    "id": 82,
    "short_name": "DE",
    "name": "Germany"
  }, {
    "id": 83,
    "short_name": "GH",
    "name": "Ghana"
  }, {
    "id": 84,
    "short_name": "GI",
    "name": "Gibraltar"
  }, {
    "id": 85,
    "short_name": "GR",
    "name": "Greece"
  }, {
    "id": 86,
    "short_name": "GL",
    "name": "Greenland"
  }, {
    "id": 87,
    "short_name": "GD",
    "name": "Grenada"
  }, {
    "id": 88,
    "short_name": "GP",
    "name": "Guadeloupe"
  }, {
    "id": 89,
    "short_name": "GU",
    "name": "Guam"
  }, {
    "id": 90,
    "short_name": "GT",
    "name": "Guatemala"
  }, {
    "id": 91,
    "short_name": "GN",
    "name": "Guinea"
  }, {
    "id": 92,
    "short_name": "GW",
    "name": "Guinea-Bissau"
  }, {
    "id": 93,
    "short_name": "GY",
    "name": "Guyana"
  }, {
    "id": 94,
    "short_name": "HT",
    "name": "Haiti"
  }, {
    "id": 95,
    "short_name": "HM",
    "name": "Heard and Mc Donald Islands"
  }, {
    "id": 96,
    "short_name": "HN",
    "name": "Honduras"
  }, {
    "id": 97,
    "short_name": "HK",
    "name": "Hong Kong"
  }, {
    "id": 98,
    "short_name": "HU",
    "name": "Hungary"
  }, {
    "id": 99,
    "short_name": "IS",
    "name": "Iceland"
  }, {
    "id": 100,
    "short_name": "IN",
    "name": "India"
  }, {
    "id": 101,
    "short_name": "ID",
    "name": "Indonesia"
  }, {
    "id": 102,
    "short_name": "IR",
    "name": "Iran (Islamic Republic of)"
  }, {
    "id": 103,
    "short_name": "IQ",
    "name": "Iraq"
  }, {
    "id": 104,
    "short_name": "IE",
    "name": "Ireland"
  }, {
    "id": 105,
    "short_name": "IL",
    "name": "Israel"
  }, {
    "id": 106,
    "short_name": "IT",
    "name": "Italy"
  }, {
    "id": 107,
    "short_name": "CI",
    "name": "Ivory Coast"
  }, {
    "id": 108,
    "short_name": "JM",
    "name": "Jamaica"
  }, {
    "id": 109,
    "short_name": "JP",
    "name": "Japan"
  }, {
    "id": 110,
    "short_name": "JO",
    "name": "Jordan"
  }, {
    "id": 111,
    "short_name": "KZ",
    "name": "Kazakhstan"
  }, {
    "id": 112,
    "short_name": "KE",
    "name": "Kenya"
  }, {
    "id": 113,
    "short_name": "KI",
    "name": "Kiribati"
  }, {
    "id": 114,
    "short_name": "KP",
    "name": "Korea, Democratic People\\'s Republic of"
  }, {
    "id": 115,
    "short_name": "KR",
    "name": "Korea, Republic of"
  }, {
    "id": 116,
    "short_name": "KW",
    "name": "Kuwait"
  }, {
    "id": 117,
    "short_name": "KG",
    "name": "Kyrgyzstan"
  }, {
    "id": 118,
    "short_name": "LA",
    "name": "Lao People\\'s Democratic Republic"
  }, {
    "id": 119,
    "short_name": "LV",
    "name": "Latvia"
  }, {
    "id": 120,
    "short_name": "LB",
    "name": "Lebanon"
  }, {
    "id": 121,
    "short_name": "LS",
    "name": "Lesotho"
  }, {
    "id": 122,
    "short_name": "LR",
    "name": "Liberia"
  }, {
    "id": 123,
    "short_name": "LY",
    "name": "Libyan Arab Jamahiriya"
  }, {
    "id": 124,
    "short_name": "LI",
    "name": "Liechtenstein"
  }, {
    "id": 125,
    "short_name": "LT",
    "name": "Lithuania"
  }, {
    "id": 126,
    "short_name": "LU",
    "name": "Luxembourg"
  }, {
    "id": 127,
    "short_name": "MO",
    "name": "Macau"
  }, {
    "id": 128,
    "short_name": "MK",
    "name": "Macedonia"
  }, {
    "id": 129,
    "short_name": "MG",
    "name": "Madagascar"
  }, {
    "id": 130,
    "short_name": "MW",
    "name": "Malawi"
  }, {
    "id": 131,
    "short_name": "MY",
    "name": "Malaysia"
  }, {
    "id": 132,
    "short_name": "MV",
    "name": "Maldives"
  }, {
    "id": 133,
    "short_name": "ML",
    "name": "Mali"
  }, {
    "id": 134,
    "short_name": "MT",
    "name": "Malta"
  }, {
    "id": 135,
    "short_name": "MH",
    "name": "Marshall Islands"
  }, {
    "id": 136,
    "short_name": "MQ",
    "name": "Martinique"
  }, {
    "id": 137,
    "short_name": "MR",
    "name": "Mauritania"
  }, {
    "id": 138,
    "short_name": "MU",
    "name": "Mauritius"
  }, {
    "id": 139,
    "short_name": "TY",
    "name": "Mayotte"
  }, {
    "id": 140,
    "short_name": "MX",
    "name": "Mexico"
  }, {
    "id": 141,
    "short_name": "FM",
    "name": "Micronesia, Federated States of"
  }, {
    "id": 142,
    "short_name": "MD",
    "name": "Moldova, Republic of"
  }, {
    "id": 143,
    "short_name": "MC",
    "name": "Monaco"
  }, {
    "id": 144,
    "short_name": "MN",
    "name": "Mongolia"
  }, {
    "id": 145,
    "short_name": "MS",
    "name": "Montserrat"
  }, {
    "id": 146,
    "short_name": "MA",
    "name": "Morocco"
  }, {
    "id": 147,
    "short_name": "MZ",
    "name": "Mozambique"
  }, {
    "id": 148,
    "short_name": "MM",
    "name": "Myanmar"
  }, {
    "id": 149,
    "short_name": "NA",
    "name": "Namibia"
  }, {
    "id": 150,
    "short_name": "NR",
    "name": "Nauru"
  }, {
    "id": 151,
    "short_name": "NP",
    "name": "Nepal"
  }, {
    "id": 152,
    "short_name": "NL",
    "name": "Netherlands"
  }, {
    "id": 153,
    "short_name": "AN",
    "name": "Netherlands Antilles"
  }, {
    "id": 154,
    "short_name": "NC",
    "name": "New Caledonia"
  }, {
    "id": 155,
    "short_name": "NZ",
    "name": "New Zealand"
  }, {
    "id": 156,
    "short_name": "NI",
    "name": "Nicaragua"
  }, {
    "id": 157,
    "short_name": "NE",
    "name": "Niger"
  }, {
    "id": 158,
    "short_name": "NG",
    "name": "Nigeria"
  }, {
    "id": 159,
    "short_name": "NU",
    "name": "Niue"
  }, {
    "id": 160,
    "short_name": "NF",
    "name": "Norfork Island"
  }, {
    "id": 161,
    "short_name": "MP",
    "name": "Northern Mariana Islands"
  }, {
    "id": 162,
    "short_name": "NO",
    "name": "Norway"
  }, {
    "id": 163,
    "short_name": "OM",
    "name": "Oman"
  }, {
    "id": 164,
    "short_name": "PK",
    "name": "Pakistan"
  }, {
    "id": 165,
    "short_name": "PW",
    "name": "Palau"
  }, {
    "id": 166,
    "short_name": "PA",
    "name": "Panama"
  }, {
    "id": 167,
    "short_name": "PG",
    "name": "Papua New Guinea"
  }, {
    "id": 168,
    "short_name": "PY",
    "name": "Paraguay"
  }, {
    "id": 169,
    "short_name": "PE",
    "name": "Peru"
  }, {
    "id": 170,
    "short_name": "PH",
    "name": "Philippines"
  }, {
    "id": 171,
    "short_name": "PN",
    "name": "Pitcairn"
  }, {
    "id": 172,
    "short_name": "PL",
    "name": "Poland"
  }, {
    "id": 173,
    "short_name": "PT",
    "name": "Portugal"
  }, {
    "id": 174,
    "short_name": "PR",
    "name": "Puerto Rico"
  }, {
    "id": 175,
    "short_name": "QA",
    "name": "Qatar"
  }, {
    "id": 176,
    "short_name": "SS",
    "name": "Republic of South Sudan"
  }, {
    "id": 177,
    "short_name": "RE",
    "name": "Reunion"
  }, {
    "id": 178,
    "short_name": "RO",
    "name": "Romania"
  }, {
    "id": 179,
    "short_name": "RU",
    "name": "Russian Federation"
  }, {
    "id": 180,
    "short_name": "RW",
    "name": "Rwanda"
  }, {
    "id": 181,
    "short_name": "KN",
    "name": "Saint Kitts and Nevis"
  }, {
    "id": 182,
    "short_name": "LC",
    "name": "Saint Lucia"
  }, {
    "id": 183,
    "short_name": "VC",
    "name": "Saint Vincent and the Grenadines"
  }, {
    "id": 184,
    "short_name": "WS",
    "name": "Samoa"
  }, {
    "id": 185,
    "short_name": "SM",
    "name": "San Marino"
  }, {
    "id": 186,
    "short_name": "ST",
    "name": "Sao Tome and Principe"
  }, {
    "id": 187,
    "short_name": "SA",
    "name": "Saudi Arabia"
  }, {
    "id": 188,
    "short_name": "SN",
    "name": "Senegal"
  }, {
    "id": 189,
    "short_name": "RS",
    "name": "Serbia"
  }, {
    "id": 190,
    "short_name": "SC",
    "name": "Seychelles"
  }, {
    "id": 191,
    "short_name": "SL",
    "name": "Sierra Leone"
  }, {
    "id": 192,
    "short_name": "SG",
    "name": "Singapore"
  }, {
    "id": 193,
    "short_name": "SK",
    "name": "Slovakia"
  }, {
    "id": 194,
    "short_name": "SI",
    "name": "Slovenia"
  }, {
    "id": 195,
    "short_name": "SB",
    "name": "Solomon Islands"
  }, {
    "id": 196,
    "short_name": "SO",
    "name": "Somalia"
  }, {
    "id": 197,
    "short_name": "ZA",
    "name": "South Africa"
  }, {
    "id": 198,
    "short_name": "GS",
    "name": "South Georgia South Sandwich Islands"
  }, {
    "id": 199,
    "short_name": "ES",
    "name": "Spain"
  }, {
    "id": 200,
    "short_name": "LK",
    "name": "Sri Lanka"
  }, {
    "id": 201,
    "short_name": "SH",
    "name": "St. Helena"
  }, {
    "id": 202,
    "short_name": "PM",
    "name": "St. Pierre and Miquelon"
  }, {
    "id": 203,
    "short_name": "SD",
    "name": "Sudan"
  }, {
    "id": 204,
    "short_name": "SR",
    "name": "Suriname"
  }, {
    "id": 205,
    "short_name": "SJ",
    "name": "Svalbarn and Jan Mayen Islands"
  }, {
    "id": 206,
    "short_name": "SZ",
    "name": "Swaziland"
  }, {
    "id": 207,
    "short_name": "SE",
    "name": "Sweden"
  }, {
    "id": 208,
    "short_name": "CH",
    "name": "Switzerland"
  }, {
    "id": 209,
    "short_name": "SY",
    "name": "Syrian Arab Republic"
  }, {
    "id": 210,
    "short_name": "TW",
    "name": "Taiwan"
  }, {
    "id": 211,
    "short_name": "TJ",
    "name": "Tajikistan"
  }, {
    "id": 212,
    "short_name": "TZ",
    "name": "Tanzania, United Republic of"
  }, {
    "id": 213,
    "short_name": "TH",
    "name": "Thailand"
  }, {
    "id": 214,
    "short_name": "TG",
    "name": "Togo"
  }, {
    "id": 215,
    "short_name": "TK",
    "name": "Tokelau"
  }, {
    "id": 216,
    "short_name": "TO",
    "name": "Tonga"
  }, {
    "id": 217,
    "short_name": "TT",
    "name": "Trinidad and Tobago"
  }, {
    "id": 218,
    "short_name": "TN",
    "name": "Tunisia"
  }, {
    "id": 219,
    "short_name": "TR",
    "name": "Turkey"
  }, {
    "id": 220,
    "short_name": "TM",
    "name": "Turkmenistan"
  }, {
    "id": 221,
    "short_name": "TC",
    "name": "Turks and Caicos Islands"
  }, {
    "id": 222,
    "short_name": "TV",
    "name": "Tuvalu"
  }, {
    "id": 223,
    "short_name": "UG",
    "name": "Uganda"
  }, {
    "id": 224,
    "short_name": "UA",
    "name": "Ukraine"
  }, {
    "id": 225,
    "short_name": "AE",
    "name": "United Arab Emirates"
  }, {
    "id": 226,
    "short_name": "GB",
    "name": "United Kingdom"
  }, {
    "id": 227,
    "short_name": "UM",
    "name": "United States minor outlying islands"
  }, {
    "id": 228,
    "short_name": "UY",
    "name": "Uruguay"
  }, {
    "id": 229,
    "short_name": "UZ",
    "name": "Uzbekistan"
  }, {
    "id": 230,
    "short_name": "VU",
    "name": "Vanuatu"
  }, {
    "id": 231,
    "short_name": "VA",
    "name": "Vatican City State"
  }, {
    "id": 232,
    "short_name": "VE",
    "name": "Venezuela"
  }, {
    "id": 233,
    "short_name": "VN",
    "name": "Vietnam"
  }, {
    "id": 234,
    "short_name": "VG",
    "name": "Virgin Islands (British)"
  }, {
    "id": 235,
    "short_name": "VI",
    "name": "Virgin Islands (U.S.)"
  }, {
    "id": 236,
    "short_name": "WF",
    "name": "Wallis and Futuna Islands"
  }, {
    "id": 237,
    "short_name": "EH",
    "name": "Western Sahara"
  }, {
    "id": 238,
    "short_name": "YE",
    "name": "Yemen"
  }, {
    "id": 239,
    "short_name": "YU",
    "name": "Yugoslavia"
  }, {
    "id": 240,
    "short_name": "ZR",
    "name": "Zaire"
  }, {
    "id": 241,
    "short_name": "ZM",
    "name": "Zambia"
  }, {
    "id": 242,
    "short_name": "ZW",
    "name": "Zimbabwe"
  }]);

  await knex.raw(`select setval(\'${AddressCountries.tableName}_id_seq\', max(id)) from ${AddressCountries.tableName}`);
};